### ISSUE TITLE
New Function

### ISSUE THREAD

**Issue by ghost** [appalachianstate/moodle-local_userenrols#4]
Hi, 
i created new function to your plugin:
copy enroled users, groups, groupings and all assigments from one course to another. It is not finished, but it is working. 
[copyusers.zip](https://github.com/appalachianstate/moodle-local_userenrols/files/1695655/copyusers.zip)

**Comment by woolardfa** [comment]
Ino, thanks for the contribution. For that functionality it would be best for you to fork the project and add that code to your fork.
