### ISSUE TITLE
Groups with certain characters aren't supported

### ISSUE THREAD

**Issue by Syxton** [appalachianstate/moodle-local_userenrols#6]
If the group name is "Test (Group 1)" an error is given:

Unable to parse the line contents 'testuser@local.host	"Test (Group 1)"'

There may be other characters that Moodle accepts but this tool does not

**Comment by woolardfa** [comment]
True, the second capturing group in the validation regex is overly restrictive. If creating groups from the import file, then the group names can be edited afterward. The regex for the group name is "[a-z0-9][\w\' .,&-]*" which allows for apostrophes, periods, commas, ampersands, and dashes. No parentheses.

**Comment by Syxton** [comment]
Pull request #7

**Comment by woolardfa** [comment]
Thank for the contribution.
