### ISSUE TITLE
Unable to parse the line contents

### ISSUE THREAD

**Issue by melanietreitinger** [appalachianstate/moodle-local_userenrols#9]
I discovered that importing a file with BOM (Byte Order Mark) does cause the plugin to fail with "Unable to parse the line contents" because it prepends the lines with `<feff>`, the unicode character for the BOM.

Should this be considered in the regex?

At least it should be mentioned in the readme file / help text!

**Comment by woolardfa** [comment]
Certainly something to consider. Concern is the regular expression becomes so convoluted in attempt to accommodate every possibility... eventually will be no point in using a regular expression to parse and validate.

Making explicit mention of the issue might be warranted. But to clarify, I am under the impression the BOM appears at the beginning of each file, or stream. Is that not correct? If you are seeing that character at the beginning of each line, then might there be an issue with how the file has been constructed? Seems as though it is a concatenation of several streams, each with a BOM and one line of text. I would think the correct formatting would be a single BOM at the beginning of the file, then the file content separated by LF, or CRLF.

**Comment by melanietreitinger** [comment]
I understand your concern that the regex becomes too complex.
You could though make two separate regex checks - the first to identify if there is a BOM and then proceed with the rest as it is now.

The BOM only appears once at the beginning of the file: https://en.wikipedia.org/wiki/Byte_order_mark
(I tested with a single line...)

**Comment by woolardfa** [comment]
@melanietreitinger, thanks for pointing out this issue. Doing a little more checking, seemed the simplest solution was to just strip any possible BOM chars at the same time as any other whitespace chars from line ends. The [2c3eaa4 ](https://github.com/appalachianstate/moodle-local_userenrols/commit/2c3eaa4817a6de24a6b208c772b742681276543c) commit in master has this change.
